import os
import sqlite3
import psycopg
from psycopg.rows import dict_row
import bcrypt

# Safe import for Tkinter (making it optional for cloud deployment)
try:
    import tkinter as tk
    from tkinter import messagebox, ttk
    TKINTER_AVAILABLE = True
except ImportError:
    tk = None
    messagebox = None
    ttk = None
    TKINTER_AVAILABLE = False


class DatabaseManager:
    def __init__(self, db_name="hardware_inventory.db"):
        self.db_name = db_name
        self.db_url = os.getenv("DATABASE_URL")
        self.is_postgres = bool(self.db_url)
        self.init_db()

    def get_connection(self):
        if self.is_postgres:
            return psycopg.connect(self.db_url, row_factory=dict_row)
        else:
            conn = sqlite3.connect(self.db_name)
            conn.row_factory = sqlite3.Row
            return conn

    def init_db(self):
        conn = self.get_connection()
        cur = conn.cursor()
        
        if self.is_postgres:
            cur.execute("""
                CREATE TABLE IF NOT EXISTS users (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    username TEXT UNIQUE NOT NULL,
                    email TEXT NOT NULL DEFAULT 'user@campus.edu',
                    password_hash TEXT NOT NULL,
                    role TEXT NOT NULL DEFAULT 'USER' CHECK (role IN ('ADMIN', 'USER')),
                    failed_attempts INTEGER NOT NULL DEFAULT 0,
                    is_locked INTEGER NOT NULL DEFAULT 0
                );
            """)
            cur.execute("""
                CREATE TABLE IF NOT EXISTS password_resets (
                    request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    username TEXT NOT NULL,
                    email TEXT NOT NULL,
                    new_password_hash TEXT NOT NULL,
                    request_time TEXT NOT NULL,
                    status TEXT NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED'))
                );
            """)
            cur.execute("""
                CREATE TABLE IF NOT EXISTS hardware (
                    item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    item_name TEXT NOT NULL,
                    category TEXT NOT NULL,
                    quantity INTEGER NOT NULL,
                    unit_price DOUBLE PRECISION NOT NULL,
                    status TEXT NOT NULL
                );
            """)
            cur.execute("""
                CREATE TABLE IF NOT EXISTS loans (
                    loan_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    username TEXT NOT NULL,
                    item_id BIGINT NOT NULL,
                    item_name TEXT NOT NULL,
                    borrow_date TEXT NOT NULL,
                    return_date TEXT,
                    quantity INTEGER NOT NULL DEFAULT 1,
                    status TEXT NOT NULL DEFAULT 'PENDING_BORROW' CHECK (status IN ('PENDING_BORROW', 'BORROWED', 'RETURN_PENDING', 'RETURNED'))
                );
            """)
        else:
            cur.execute("""
                CREATE TABLE IF NOT EXISTS users (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    username TEXT UNIQUE NOT NULL,
                    email TEXT NOT NULL DEFAULT 'user@campus.edu',
                    password_hash TEXT NOT NULL,
                    role TEXT NOT NULL DEFAULT 'USER',
                    failed_attempts INTEGER NOT NULL DEFAULT 0,
                    is_locked INTEGER NOT NULL DEFAULT 0
                );
            """)
            cur.execute("""
                CREATE TABLE IF NOT EXISTS password_resets (
                    request_id INTEGER PRIMARY KEY AUTOINCREMENT,
                    username TEXT NOT NULL,
                    email TEXT NOT NULL,
                    new_password_hash TEXT NOT NULL,
                    request_time TEXT NOT NULL,
                    status TEXT NOT NULL DEFAULT 'PENDING'
                );
            """)
            cur.execute("""
                CREATE TABLE IF NOT EXISTS hardware (
                    item_id INTEGER PRIMARY KEY AUTOINCREMENT,
                    item_name TEXT NOT NULL,
                    category TEXT NOT NULL,
                    quantity INTEGER NOT NULL,
                    unit_price REAL NOT NULL,
                    status TEXT NOT NULL
                );
            """)
            cur.execute("""
                CREATE TABLE IF NOT EXISTS loans (
                    loan_id INTEGER PRIMARY KEY AUTOINCREMENT,
                    username TEXT NOT NULL,
                    item_id INTEGER NOT NULL,
                    item_name TEXT NOT NULL,
                    borrow_date TEXT NOT NULL,
                    return_date TEXT,
                    quantity INTEGER NOT NULL DEFAULT 1,
                    status TEXT NOT NULL DEFAULT 'PENDING_BORROW'
                );
            """)
            
        conn.commit()
        conn.close()

    def query_all(self, query, params=()):
        conn = self.get_connection()
        cur = conn.cursor()
        cur.execute(query, params)
        rows = cur.fetchall()
        conn.close()
        return [dict(r) if self.is_postgres else dict(r) for r in rows]

    def query_one(self, query, params=()):
        conn = self.get_connection()
        cur = conn.cursor()
        cur.execute(query, params)
        row = cur.fetchone()
        conn.close()
        if row:
            return dict(row)
        return None

    def execute(self, query, params=()):
        conn = self.get_connection()
        cur = conn.cursor()
        cur.execute(query, params)
        conn.commit()
        conn.close()


class AuthSystem:
    def __init__(self, db_manager):
        self.db = db_manager

    def hash_password(self, password):
        return bcrypt.hashpw(password.encode('utf-8'), bcrypt.gensalt()).decode('utf-8')

    def verify_password(self, password, hashed):
        return bcrypt.checkpw(password.encode('utf-8'), hashed.encode('utf-8'))

    def register_user(self, username, email, password, role="USER"):
        existing = self.db.query_one("SELECT * FROM users WHERE username = %s" if self.db.is_postgres else "SELECT * FROM users WHERE username = ?", (username,))
        if existing:
            return False, "Username already exists."
        
        pw_hash = self.hash_password(password)
        q = "INSERT INTO users (username, email, password_hash, role) VALUES (%s, %s, %s, %s)" if self.db.is_postgres else "INSERT INTO users (username, email, password_hash, role) VALUES (?, ?, ?, ?)"
        self.db.execute(q, (username, email, pw_hash, role))
        return True, "User registered successfully."

    def authenticate(self, username, password):
        q = "SELECT * FROM users WHERE username = %s" if self.db.is_postgres else "SELECT * FROM users WHERE username = ?"
        user = self.db.query_one(q, (username,))
        if not user:
            return False, "User not found.", None
        
        if user['is_locked']:
            return False, "Account is locked due to too many failed login attempts.", None
        
        if self.verify_password(password, user['password_hash']):
            reset_q = "UPDATE users SET failed_attempts = 0 WHERE username = %s" if self.db.is_postgres else "UPDATE users SET failed_attempts = 0 WHERE username = ?"
            self.db.execute(reset_q, (username,))
            return True, "Login successful.", user
        else:
            attempts = user['failed_attempts'] + 1
            if attempts >= 3:
                lock_q = "UPDATE users SET failed_attempts = %s, is_locked = 1 WHERE username = %s" if self.db.is_postgres else "UPDATE users SET failed_attempts = ?, is_locked = 1 WHERE username = ?"
                self.db.execute(lock_q, (attempts, username))
                return False, "Account locked after 3 failed attempts.", None
            else:
                inc_q = "UPDATE users SET failed_attempts = %s WHERE username = %s" if self.db.is_postgres else "UPDATE users SET failed_attempts = ? WHERE username = ?"
                self.db.execute(inc_q, (attempts, username))
                return False, f"Invalid password. Attempt {attempts}/3.", None


class InventoryManager:
    def __init__(self, db_manager):
        self.db = db_manager

    def add_item(self, item_name, category, quantity, unit_price):
        status = "In Stock" if quantity > 10 else ("Low Stock" if quantity > 0 else "Out of Stock")
        q = "INSERT INTO hardware (item_name, category, quantity, unit_price, status) VALUES (%s, %s, %s, %s, %s)" if self.db.is_postgres else "INSERT INTO hardware (item_name, category, quantity, unit_price, status) VALUES (?, ?, ?, ?, ?)"
        self.db.execute(q, (item_name, category, quantity, unit_price, status))

    def update_item(self, item_id, item_name, category, quantity, unit_price):
        status = "In Stock" if quantity > 10 else ("Low Stock" if quantity > 0 else "Out of Stock")
        q = "UPDATE hardware SET item_name = %s, category = %s, quantity = %s, unit_price = %s, status = %s WHERE item_id = %s" if self.db.is_postgres else "UPDATE hardware SET item_name = ?, category = ?, quantity = ?, unit_price = ?, status = ? WHERE item_id = ?"
        self.db.execute(q, (item_name, category, quantity, unit_price, status, item_id))

    def delete_item(self, item_id):
        q = "DELETE FROM hardware WHERE item_id = %s" if self.db.is_postgres else "DELETE FROM hardware WHERE item_id = ?"
        self.db.execute(q, (item_id,))

    def get_all_hardware(self):
        return self.db.query_all("SELECT * FROM hardware ORDER BY item_id ASC")
    
class AuthController:
    def __init__(self, auth_system):
        self.auth_system = auth_system

    def verify_otp(self, email, otp):
        # Add your OTP verification logic here
        pass

    @staticmethod
    def register_user(username, email, password, role="User"):
        db = DatabaseManager()
        auth_system = AuthSystem(db)
        return auth_system.register_user(username, email, password, role)