import os  # Provides access to operating-system environment variables.
import sqlite3  # Provides SQLite database access for the original local database.
import psycopg  # Provides PostgreSQL database access.
from psycopg import sql  # Provides safe SQL construction for table and column identifiers.

SQLITE_DB = "Database.db"  # Stores the filename of the original SQLite database.
DATABASE_URL = os.getenv("DATABASE_URL")  # Reads the PostgreSQL connection string from the environment.

if not DATABASE_URL:  # Checks whether the PostgreSQL connection string was provided.
    raise RuntimeError("DATABASE_URL is not set.")  # Stops the migration if the connection string is missing.

sqlite_conn = sqlite3.connect(SQLITE_DB)  # Opens the original SQLite database.
sqlite_conn.row_factory = sqlite3.Row  # Allows SQLite rows to be accessed by column name.
pg_conn = psycopg.connect(DATABASE_URL)  # Opens a connection to the Supabase PostgreSQL database.
pg_conn.autocommit = False  # Uses a transaction so changes can be rolled back if an error occurs.

try:  # Starts the protected migration section.
    pg_cur = pg_conn.cursor()  # Creates a PostgreSQL cursor for SQL commands.
    sqlite_cur = sqlite_conn.cursor()  # Creates a SQLite cursor for reading source data.

    table_definitions = {  # Defines the PostgreSQL tables required by this application.
        "users": [  # Defines the users table.
            "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",  # Creates the user ID column.
            "username TEXT UNIQUE NOT NULL",  # Stores each user's unique username.
            "email TEXT NOT NULL DEFAULT 'user@campus.edu'",  # Stores the user's email address.
            "password_hash TEXT NOT NULL",  # Stores the hashed password.
            "role TEXT NOT NULL DEFAULT 'USER' CHECK (role IN ('ADMIN', 'USER'))",  # Restricts the user role.
            "failed_attempts INTEGER NOT NULL DEFAULT 0",  # Stores the number of failed login attempts.
            "is_locked INTEGER NOT NULL DEFAULT 0",  # Stores whether the account is locked.
        ],  # Ends the users column definition list.

        "password_resets": [  # Defines the password reset request table.
            "request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",  # Creates the reset request ID.
            "username TEXT NOT NULL",  # Stores the username requesting the reset.
            "email TEXT NOT NULL",  # Stores the email used for the request.
            "new_password_hash TEXT NOT NULL",  # Stores the requested new password hash.
            "request_time TEXT NOT NULL",  # Stores when the request was created.
            "status TEXT NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED'))",  # Restricts reset status values.
        ],  # Ends the password reset column definition list.

        "hardware": [  # Defines the hardware inventory table.
            "item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",  # Creates the hardware item ID.
            "item_name TEXT NOT NULL",  # Stores the hardware item name.
            "category TEXT NOT NULL",  # Stores the hardware category.
            "quantity INTEGER NOT NULL",  # Stores the available stock quantity.
            "unit_price DOUBLE PRECISION NOT NULL",  # Stores the price of one unit.
            "status TEXT NOT NULL",  # Stores the calculated stock status.
        ],  # Ends the hardware column definition list.

        "loans": [  # Defines the borrowing and return table.
            "loan_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",  # Creates the loan record ID.
            "username TEXT NOT NULL",  # Stores the borrower username.
            "item_id BIGINT NOT NULL",  # Stores the borrowed hardware ID.
            "item_name TEXT NOT NULL",  # Stores the hardware name at the time of borrowing.
            "borrow_date TEXT NOT NULL",  # Stores the borrow request/borrow date.
            "return_date TEXT",  # Stores the return date when available.
            "quantity INTEGER NOT NULL DEFAULT 1",  # Stores how many units were borrowed.
            "status TEXT NOT NULL DEFAULT 'PENDING_BORROW' CHECK (status IN ('PENDING_BORROW', 'BORROWED', 'RETURN_PENDING', 'RETURNED'))",  # Restricts loan status values.
        ],  # Ends the loans column definition list.
    }  # Ends the table definition dictionary.

    for table_name, columns in table_definitions.items():  # Processes each required application table.
        column_sql = sql.SQL(", ").join(sql.SQL(column) for column in columns)  # Safely combines column definitions.
        create_sql = sql.SQL("CREATE TABLE IF NOT EXISTS {} ({})").format(sql.Identifier(table_name), column_sql)  # Builds the CREATE TABLE statement.
        pg_cur.execute(create_sql)  # Creates the table if it does not already exist.

    counts = {}  # Creates a dictionary for recording migrated row counts.

    for table_name, columns in table_definitions.items():  # Processes each table for data migration.
        pg_cur.execute(sql.SQL("SELECT COUNT(*) FROM {}").format(sql.Identifier(table_name)))  # Checks whether the destination table already has data.
        destination_count = pg_cur.fetchone()[0]  # Reads the number of existing rows.

        if destination_count > 0:  # Checks whether the destination table is already populated.
            raise RuntimeError(f"Destination table '{table_name}' is not empty.")  # Stops to prevent accidental duplicate migration.

        sqlite_cur.execute(sql.SQL("SELECT * FROM {}").format(sql.Identifier(table_name)))  # Reads all rows from the matching SQLite table.
        rows = sqlite_cur.fetchall()  # Stores the source rows in memory.
        counts[table_name] = len(rows)  # Records how many rows will be migrated.

        if not rows:  # Checks whether the source table has no rows.
            continue  # Moves to the next table when there is nothing to copy.

        source_columns = [description[0] for description in sqlite_cur.description]  # Gets the SQLite column names.
        insert_columns = source_columns[:]  # Makes a copy of the source column list for the INSERT statement.

        if table_name == "loans" and "quantity" not in insert_columns:  # Checks for an older loans table without quantity.
            insert_columns.append("quantity")  # Adds quantity so older records can still be migrated.

        column_identifiers = sql.SQL(", ").join(sql.Identifier(column) for column in insert_columns)  # Safely builds the INSERT column list.
        placeholders = sql.SQL(", ").join(sql.Placeholder() for _ in insert_columns)  # Creates one PostgreSQL placeholder per value.
        insert_sql = sql.SQL("INSERT INTO {} ({}) VALUES ({})").format(sql.Identifier(table_name), column_identifiers, placeholders)  # Builds the INSERT statement.

        for row in rows:  # Processes every source row.
            values = [row[column] for column in source_columns]  # Gets the source values in column order.

            if table_name == "loans" and "quantity" not in source_columns:  # Checks again for legacy loan records.
                values.append(1)  # Gives older loan records a default quantity of one.

            pg_cur.execute(insert_sql, values)  # Inserts the current row into PostgreSQL.

    sequence_columns = {  # Maps each table to its identity ID column.
        "users": "id",  # Identifies the users primary key column.
        "password_resets": "request_id",  # Identifies the password reset primary key column.
        "hardware": "item_id",  # Identifies the hardware primary key column.
        "loans": "loan_id",  # Identifies the loan primary key column.
    }  # Ends the identity column mapping.

    for table_name, id_column in sequence_columns.items():  # Processes each identity column.
        sequence_sql = sql.SQL("SELECT setval(pg_get_serial_sequence({}, {}), COALESCE(MAX({}), 0), MAX({}) IS NOT NULL) FROM {}").format(  # Builds SQL to synchronize the identity sequence with the migrated IDs.
            sql.Literal(table_name),  # Supplies the table name as a SQL value.
            sql.Literal(id_column),  # Supplies the ID column name as a SQL value.
            sql.Identifier(id_column),  # Supplies the ID column as an SQL identifier for MAX.
            sql.Identifier(id_column),  # Supplies the ID column again for the sequence state test.
            sql.Identifier(table_name),  # Supplies the table name as an SQL identifier.
        )  # Finishes the sequence SQL construction.
        pg_cur.execute(sequence_sql)  # Updates the identity sequence after explicit IDs were inserted.

    pg_conn.commit()  # Permanently saves all migrated tables and rows.
    print("Migration completed successfully.")  # Reports that the migration finished.
    print(f"  users:            {counts['users']}")  # Displays the number of migrated users.
    print(f"  password_resets:  {counts['password_resets']}")  # Displays the number of migrated reset requests.
    print(f"  hardware:         {counts['hardware']}")  # Displays the number of migrated hardware records.
    print(f"  loans:             {counts['loans']}")  # Displays the number of migrated loan records.

except Exception:  # Catches any error during migration.
    pg_conn.rollback()  # Cancels PostgreSQL changes made during the failed transaction.
    raise  # Re-raises the original error so the student can see the problem.

finally:  # Runs cleanup whether migration succeeds or fails.
    sqlite_conn.close()  # Closes the SQLite database connection.
    pg_conn.close()  # Closes the PostgreSQL database connection.
