import os
import sqlite3
import psycopg
from psycopg import sql

SQLITE_DB = "hardware_inventory.db"
DATABASE_URL = os.getenv("DATABASE_URL")

if not DATABASE_URL:
    raise RuntimeError("DATABASE_URL is not set.")

sqlite_conn = sqlite3.connect(SQLITE_DB)
sqlite_conn.row_factory = sqlite3.Row

pg_conn = psycopg.connect(DATABASE_URL)
pg_conn.autocommit = False

try:
    pg_cur = pg_conn.cursor()
    sqlite_cur = sqlite_conn.cursor()

    table_definitions = {
        "users": [
            "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
            "username TEXT UNIQUE NOT NULL",
            "email TEXT NOT NULL DEFAULT 'user@campus.edu'",
            "password_hash TEXT NOT NULL",
            "role TEXT NOT NULL DEFAULT 'USER' CHECK (role IN ('ADMIN', 'USER'))",
            "failed_attempts INTEGER NOT NULL DEFAULT 0",
            "is_locked INTEGER NOT NULL DEFAULT 0",
        ],
        "password_resets": [
            "request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
            "username TEXT NOT NULL",
            "email TEXT NOT NULL",
            "new_password_hash TEXT NOT NULL",
            "request_time TEXT NOT NULL",
            "status TEXT NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED'))",
        ],
        "hardware": [
            "item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
            "item_name TEXT NOT NULL",
            "category TEXT NOT NULL",
            "quantity INTEGER NOT NULL",
            "unit_price DOUBLE PRECISION NOT NULL",
            "status TEXT NOT NULL",
        ],
        "loans": [
            "loan_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
            "username TEXT NOT NULL",
            "item_id BIGINT NOT NULL",
            "item_name TEXT NOT NULL",
            "borrow_date TEXT NOT NULL",
            "return_date TEXT",
            "quantity INTEGER NOT NULL DEFAULT 1",
            "status TEXT NOT NULL DEFAULT 'PENDING_BORROW' CHECK (status IN ('PENDING_BORROW', 'BORROWED', 'RETURN_PENDING', 'RETURNED'))",
        ],
    }

    for table_name, columns in table_definitions.items():
        column_sql = sql.SQL(", ").join(sql.SQL(column) for column in columns)
        create_sql = sql.SQL("CREATE TABLE IF NOT EXISTS {} ({})").format(sql.Identifier(table_name), column_sql)
        pg_cur.execute(create_sql)

    counts = {}
    for table_name, columns in table_definitions.items():
        pg_cur.execute(sql.SQL("SELECT COUNT(*) FROM {}").format(sql.Identifier(table_name)))
        destination_count = pg_cur.fetchone()[0]
        if destination_count > 0:
            raise RuntimeError(f"Destination table '{table_name}' is not empty.")

        sqlite_cur.execute(sql.SQL("SELECT * FROM {}").format(sql.Identifier(table_name)))
        rows = sqlite_cur.fetchall()
        counts[table_name] = len(rows)

        if not rows:
            continue

        source_columns = [description[0] for description in sqlite_cur.description]
        insert_columns = source_columns[:]

        if table_name == "loans" and "quantity" not in insert_columns:
            insert_columns.append("quantity")

        column_identifiers = sql.SQL(", ").join(sql.Identifier(column) for column in insert_columns)
        placeholders = sql.SQL(", ").join(sql.Placeholder() for _ in insert_columns)
        insert_sql = sql.SQL("INSERT INTO {} ({}) VALUES ({})").format(sql.Identifier(table_name), column_identifiers, placeholders)

        for row in rows:
            values = [row[column] for column in source_columns]
            if table_name == "loans" and "quantity" not in source_columns:
                values.append(1)
            pg_cur.execute(insert_sql, values)

    sequence_columns = {
        "users": "id",
        "password_resets": "request_id",
        "hardware": "item_id",
        "loans": "loan_id",
    }

    for table_name, id_column in sequence_columns.items():
        sequence_sql = sql.SQL("SELECT setval(pg_get_serial_sequence({}, {}), COALESCE(MAX({}), 0), MAX({}) IS NOT NULL) FROM {}").format(
            sql.Literal(table_name),
            sql.Literal(id_column),
            sql.Identifier(id_column),
            sql.Identifier(id_column),
            sql.Identifier(table_name),
        )
        pg_cur.execute(sequence_sql)

    pg_conn.commit()
    print("Migration completed successfully.")
    print(f"  users:            {counts['users']}")
    print(f"  password_resets:  {counts['password_resets']}")
    print(f"  hardware:         {counts['hardware']}")
    print(f"  loans:            {counts['loans']}")

except Exception:
    pg_conn.rollback()
    raise
finally:
    sqlite_conn.close()
    pg_conn.close()